apply plugin: 'org.springframework.boot'

dependencies {
	implementation project(':common')
	implementation 'org.springframework.boot:spring-boot-starter-webflux:3.1.5'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive:3.1.5'
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc:3.1.5'
	implementation 'org.springframework.kafka:spring-kafka:3.1.1'
	implementation 'org.postgresql:r2dbc-postgresql:1.0.2.RELEASE'

	implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.3'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.3'

	testImplementation "org.testcontainers:testcontainers:1.19.0"
	testImplementation "org.testcontainers:junit-jupiter:1.19.0"
	testImplementation "org.testcontainers:kafka:1.19.0"
	testImplementation "org.testcontainers:postgresql:1.19.0"
	testImplementation "org.testcontainers:r2dbc:1.19.0"
}